morse_logs/urls.py
"Defines URL patterns for morse_logs"

from django.urls import path, include
from morse_logs import views

app_name = 'morse_logs'

urlpatterns = [
    #The path() function is passed four arguments, two required: route and view, and two optional: kwargs, and name.
    # Home Page
    path(r'', views.index, name='index'),
    # Page that shows all topics
    path(r'topics/', views.topics, name='topics'),
    path(r'cipher/', views.cipher, name='cipher'),
    path(r'decipher/', views.decipher, name='decipher'),
    path(r'tutorialIndex/', views.tutorialIndex, name='tutorialIndex'),
    path(r'gameDirectory/', views.gameDirectory, name='gameDirectory'),
    path(r'correct/', views.correct, name='correct'),
    path(r'incorrect/', views.incorrect, name='incorrect'),
    path(r'game1/', views.game1, name='game1'),
    path(r'game2/', views.game2, name='game2'),
    path(r'game3/', views.game3, name='game3'),
    path(r'game4/', views.game4, name='game4'),
    path(r'game5/', views.game5, name='game5'),
    path(r'game6/', views.game6, name='game6'),
    path(r'game7/', views.game7, name='game7'),
    path(r'game8/', views.game8, name='game8'),
    path(r'game9/', views.game9, name='game9'),
    path(r'leaderboard/', views.leaderboard, name='leaderboard'),
]

morse_logs/templates/morse_logs/cipher.html
{% extends "morse_logs/base.html" %}

{% block content %}
<title>Cipher</title>
<div class="container jumbotron">
    <br/>
<p style="font-size: 65px"><strong>Cipher</strong></p>
    <div class="form-group form-group-lg">
    <form action="" method="get" >
        <br/><br/>
        <input class="form-control input-lg" name="a1" type="text" placeholder="Enter a word or sentence here">
        <br/><br/><br/>
        <div class="well well-lg">
            <output name="a2"  style="font-size: 30px"><strong>{{result}}</strong></output>
        </div>
        <br/><br/><br/>
                <button type="submit" name="cipher" class="btn-group-justified" style="font-size:18px"><strong>Cipher</strong></button>
    </form>
    </div>
</div>
{% endblock content  %}

morse_logs/templates/morse_logs/correct.html
{% extends "morse_logs/base.html" %}

{% block content %}
    <title>Correct!</title>
<div>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <p style="font-size: 55px"><strong>Congratulations! Your answer is CORRECT!</strong></p>
    <br/><br/>
    <a href="{% url 'morse_logs:gameDirectory' %}" style="font-size: 20px"><strong>Back to Game Directory</strong></a>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/decipher.html
{% extends "morse_logs/base.html" %}

{% block content %}
<title>Cipher</title>
<div class="container jumbotron">
    <br/>
<p style="font-size: 65px"><strong>Decipher</strong></p>
    <div class="form-group form-group-lg">
    <form action="" method="get" >
<!--        <input class="form-control input-lg" id="inputlg" type="text" name="a1">-->
        <br/><br/>
        <input class="form-control input-lg" name="a1" type="text" placeholder="Enter a morse code here ( . or - only )">
        <br/><br/><br/>
        <div class="well well-lg">
            <output name="a2"  style="font-size: 30px;"><strong>{{result}}</strong></output>
        </div>
        <br/><br/><br/>
        <button type="submit" name="decipher" class="btn-group-justified" style="font-size:18px"><strong>Decipher</strong></button>
    </form>
    </div>
</div>
{% endblock content  %}

morse_logs/templates/morse_logs/game2.html
{% extends "morse_logs/base.html" %}

{% block content %}
<div class="jumbotron">
    <h1>GAME 2</h1>
    <br/><br/>
    <div class="well" style="text-align: center;">
    <h2>What the alphabet of Morse Code -..-</h2>
    <form method="POST">
        {% csrf_token %}
        <input id="ans2" name="ans2"/><br><br>
        <input type="submit" name="Submit"/>
    </form>
    </div>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/game4.html
{% extends "morse_logs/base.html" %}

{% block content %}
    <title>GAME 4</title>
<div class="jumbotron">
    <h1>GAME 4</h1>
    <br/><br/>
    <div class="well" style="text-align: center;">
    <h2>What is the Morse Code of 'HEY'</h2>
    <form method="POST">
        {% csrf_token %}
        <input id="ans2" name="ans2"/><br><br>
        <input type="submit" name="Submit"/>
    </form>
    </div>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/game5.html
{% extends "morse_logs/base.html" %}

{% block content %}
    <title>GAME 5</title>
<div class="jumbotron">
    <h1>GAME 5</h1>
    <br/><br/>
    <div class="well" style="text-align: center;">
    <h2>What the word in English of Morse Code .... . .-.. .--.</h2>
    <form method="POST">
        {% csrf_token %}
        <input id="ans2" name="ans2"/><br><br>
        <input type="submit" name="Submit"/>
    </form>
    </div>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/game6.html
{% extends "morse_logs/base.html" %}

{% block content %}
{% load static %}

    <title>GAME 6</title>
<div>
<div class="jumbotron">
    <h1>GAME 6</h1>
    <br/><br/>
    <div class="well" style="text-align: center;">
    <h2>What is the alphabet of this Morse Code sound?</h2>
    <audio controls>
        <source src="{% static 'morse_logs/audio/sos.mp3' %}" type="audio/mp3">
    </audio>
        <br/> <br/>
    <form method="POST">
        {% csrf_token %}
        <input id="ans2" name="ans2"/><br><br>
        <input type="submit" name="Submit"/>
    </form>
    </div>
</div>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/game7.html
{% extends "morse_logs/base.html" %}

{% block content %}
    <title>GAME 7</title>
<div class="jumbotron">
    <h1>GAME 7</h1>
    <br/><br/>
    <div class="well" style="text-align: center;">
    <h2>What is the Morse Code of 'm8'</h2>
    <form method="POST">
        {% csrf_token %}
        <input id="ans2" name="ans2"/><br><br>
        <input type="submit" name="Submit"/>
    </form>
    </div>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/game8.html
{% extends "morse_logs/base.html" %}

{% block content %}
    <title>GAME 8</title>
<div class="jumbotron">
    <h1>GAME 8</h1>
    <br/><br/>
    <div class="well" style="text-align: center;">
    <h2>What the alphabet of Morse Code .. .-.. --- ...- . -.-- --- ..-</h2>
        <br/>
    <form method="POST">
        {% csrf_token %}
        <input id="ans2" name="ans2"/><br><br>
        <input type="submit" name="Submit"/>
    </form>
    </div>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/game9.html
{% extends "morse_logs/base.html" %}

{% block content %}
{% load static %}

    <title>GAME 9</title>
<div>
<div class="jumbotron">
    <h1>GAME 9</h1>
    <br/><br/>
    <div class="well" style="text-align: center;">
    <h2>What is the sentence of this Morse Code sound?</h2>
    <audio controls>
        <source src="{% static 'morse_logs/audio/iLoveYou.mp3' %}" type="audio/mp3">
    </audio>
        <br/> <br/>
    <form method="POST">
        {% csrf_token %}
        <input id="ans2" name="ans2"/><br><br>
        <input type="submit" name="Submit"/>
    </form>
    </div>
</div>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/gameDirectory.html
{% extends "morse_logs/base.html" %}

{% block content %}
{% load static %}
<title>Game Index</title>
<div class="container jumbotron">
    <p style="font-size: 65px"><strong>Game Directory</strong></p>
    <div class="panel panel-success">
        <div class="panel-heading"><output style="font-size: 22px"><strong>Your Current Score:</strong></output></div>
        <div class="panel-body"><output name="a2"  style="font-size: 30px"><strong>{{currentS.score}}</strong></output></div>

    </div>
    <div class="  well">
        <h3>Scoring system:</h3>
        <h4>-> Beginner's level: +5</h4>
        <h4>-> Intermediate's level: +10</h4>
        <h4>-> Expert's level: +15</h4>

    </div>

        <br/>
        <h2><strong>Beginner</strong></h2>
        <div class="well">
            <a href="{% url 'morse_logs:game1' %}">Game 1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
            <a href="{% url 'morse_logs:game2' %}">Game 2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
            <a href="{% url 'morse_logs:game3' %}">Game 3</a>
        </div>
        <h2><strong>Intermediate</strong></h2>
        <div class="well">
            <a href="{% url 'morse_logs:game4' %}">Game 4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
            <a href="{% url 'morse_logs:game5' %}">Game 5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
            <a href="{% url 'morse_logs:game6' %}">Game 6</a>
        </div>
        <h2><strong>Expert</strong></h2>
        <div class="well">
            <a href="{% url 'morse_logs:game7' %}">Game 7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
            <a href="{% url 'morse_logs:game8' %}">Game 8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
            <a href="{% url 'morse_logs:game9' %}">Game 9</a>
        </div>
    </div>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/incorrect.html
{% extends "morse_logs/base.html" %}

{% block content %}
    <title>Inorrect...</title>
<div>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <p style="font-size: 55px"><strong>Unfortunately! Your answer is Incorrect!</strong></p>
    <br/><br/>
    <a href="{% url 'morse_logs:gameDirectory' %}" style="font-size: 20px"><strong>Back to Game Directory</strong></a>
</div>
{% endblock content %}

morse_logs/templates/morse_logs/leaderboard.html
{% extends "morse_logs/base.html" %}

{% block content %}
<title>Leaderboard</title>
<div class="container jumbotron" >
    <p style="font-size: 65px"><strong>Leaderboard</strong></p>
    <div>
        <table class="table table-striped table-hover" style="width:90%" border="1">
            <tr>
                <th style="background-color: #2d2d30; color: #f3f5f2; height: 80px; font-size: 25px">Ranking</th>
                <th style="background-color: #2d2d30; color: #f3f5f2; font-size: 25px">Username</th>
                <th style="background-color: #2d2d30; color: #f3f5f2; font-size: 25px">Score</th>
            </tr>
            {% for s in topFiveUserScores%}
            <tr>
                <td style="height: 75px; font-size: 25px">{{forloop.counter}}</td>
                <td style="height: 40px; font-size: 25px">{{s.user}}</td>
                <td style="height: 40px; font-size: 25px">{{s.score }}</td>
            </tr>
            {% endfor%}

        </table>

    </div>

</div>
{% endblock content  %}