morse_log/morse_log/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from morse_logs import views

urlpatterns = [
    #path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    #including the file urls.py from users, this line will match any URL that start with the word 'users'
    #e.g. http://localhost:8000/users/login/
    path('users', include('users.urls')),

    path('', include('morse_logs.urls')),

    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

morse_log/morse_logs/urls.py
"Defines URL patterns for morse_logs"

from django.urls import path, include
from django.conf.urls import url
from . import views
from morse_logs import views



app_name = 'morse_logs'

urlpatterns = [
    #The path() function is passed four arguments, two required: route and view, and two optional: kwargs, and name.
    # Home Page
    path(r'', views.index, name='index'),
    # Page that shows all topics
    path(r'topics/', views.topics, name='topics'),
    path(r'cipher/', views.cipher, name='cipher'),
    path(r'decipher/', views.decipher, name='decipher'),
    path(r'tutorialIndex/', views.tutorialIndex, name='tutorialIndex'),
    path(r'gameDirectory/', views.gameDirectory, name='gameDirectory'),
    path(r'game1/', views.game1, name='game1'),

]

morse_log/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from morse_logs import views

urlpatterns = [
    #path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    #including the file urls.py from users, this line will match any URL that start with the word 'users'
    #e.g. http://localhost:8000/users/login/
    path('users', include('users.urls')),

    path('', include('morse_logs.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

morse_log/users/urls.py
"""Defines URL pattern for users"""
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.models import User
from django.contrib.auth.views import (
    PasswordResetView, # suggestion: PasswordResetView
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

from . import views


app_name = 'users'

urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),

    # Registration
    path(r'register/', views.register, name='register'),
    path(r'profile/', views.view_profile, name='view_profile'),
    path(r'profile/edit', views.edit_profile, name='edit_profile'),
    path(r'change_password', views.change_password, name='change_password'),
    # django package to do reset password and reverse reset password
    path(r'reset_password', PasswordResetView.as_view(), name='reset_password'),
    path(r'reset_password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(r'reset_password/confirm', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path(r'reset_password/complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

morse_log/morse_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about, p.385"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns a string representation of the model"""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic, p.390"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        return f"{self.text[:50]}..." """only to show first 50 characters of text"""

morse_log/morse_log/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect(r'/users/login')

morse_log/morse_logs/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse

from users.models import userScore
from .models import Topic
from django.contrib.auth.decorators import login_required


# Create your views here.
# Business logic here
@login_required()
def index(request):
    """The home page for Morse Code Education app"""
    return render(request, 'morse_logs/index.html')

@login_required()
def topics(request):
    """The topics page"""
    """topics = Topic.objects.order_by('date_added')"""
    context = {'topics': topics}
    return render(request, 'morse_logs/topics.html', context)

@login_required()
def cipher(request):
    """The Cipher page"""
    # Dictionary representing the morse code chart
    MORSE_CODE_DICT = {'A': '.-', 'B': '-...',
                       'C': '-.-.', 'D': '-..', 'E': '.',
                       'F': '..-.', 'G': '--.', 'H': '....',
                       'I': '..', 'J': '.---', 'K': '-.-',
                       'L': '.-..', 'M': '--', 'N': '-.',
                       'O': '---', 'P': '.--.', 'Q': '--.-',
                       'R': '.-.', 'S': '...', 'T': '-',
                       'U': '..-', 'V': '...-', 'W': '.--',
                       'X': '-..-', 'Y': '-.--', 'Z': '--..',

                       '1': '.----', '2': '..---', '3': '...--',
                       '4': '....-', '5': '.....', '6': '-....',
                       '7': '--...', '8': '---..', '9': '----.',
                       '0': '-----', ', ': '--..--', '.': '.-.-.-',
                       '?': '..--..', '/': '-..-.', '-': '-....-',
                       '(': '-.--.', ')': '-.--.-'}

    def encrypt(message):
        cipher = ''
        message = message.upper()
        for letter in message:
            if letter != ' ':
                cipher += MORSE_CODE_DICT[letter] + ' '
            else:
                # 1 space indicates different characters
                # and 2 indicates different words
                cipher += ' '
        return cipher

    val1 = request.GET.get('a1', '')
    res = encrypt(val1)

    return render(request, 'morse_logs/cipher.html', {'result': res})

@login_required()
def decipher(request):
    """The Decipher Page"""
    MORSE_CODE_DICT = {'A': '.-', 'B': '-...',
                       'C': '-.-.', 'D': '-..', 'E': '.',
                       'F': '..-.', 'G': '--.', 'H': '....',
                       'I': '..', 'J': '.---', 'K': '-.-',
                       'L': '.-..', 'M': '--', 'N': '-.',
                       'O': '---', 'P': '.--.', 'Q': '--.-',
                       'R': '.-.', 'S': '...', 'T': '-',
                       'U': '..-', 'V': '...-', 'W': '.--',
                       'X': '-..-', 'Y': '-.--', 'Z': '--..',

                       '1': '.----', '2': '..---', '3': '...--',
                       '4': '....-', '5': '.....', '6': '-....',
                       '7': '--...', '8': '---..', '9': '----.',
                       '0': '-----', ', ': '--..--', '.': '.-.-.-',
                       '?': '..--..', '/': '-..-.', '-': '-....-',
                       '(': '-.--.', ')': '-.--.-'}
    # https://stackoverflow.com/questions/483666/reverse-invert-a-dictionary-mapping
    MORSE_CODE_DICT_REV = {v: k for k, v in MORSE_CODE_DICT.items()}

    def decrypt(message):
        # extra space added at the end to access the
        # last morse code
        message += ' '
        decipherMsg = ''
        citext = ''
        space = 0
        for letter in message:
            # checks for space
            if letter != ' ':
                # counter to keep track of space
                space = 0
                # storing morse code of a single character
                citext += letter
                # in case of space
            else:
                # if i = 1 that indicates a new character
                space += 1
                # if i = 2 that indicates a new word
                if space == 2:
                    # adding space to separate words
                    decipherMsg += ' '
                elif citext != '':
                    # accessing the keys using their values (reverse of encryption)
                    decipherMsg += MORSE_CODE_DICT_REV[citext]
                    citext = ''
        return decipherMsg

    val1 = request.GET.get('a1', '')
    res = decrypt(val1)

    return render(request, 'morse_logs/decipher.html', {'result': res})

@login_required()
def tutorialIndex(request):
    """The tutorial index page"""
    return render(request, 'morse_logs/tutorialIndex.html')

@login_required()
def gameDirectory(request):
    """The Game Directory page"""
    return render(request, 'morse_logs/gameDirectory.html')


@login_required()
def game1(request):

    if request.user and not request.user.is_anonymous:
        user = request.user
    #else:
        #Throw some raised exception here as the user is not valid...

    """The Game 1 page"""
    def verifyGame1(val1):
        user_score, created = userScore.objects.get_or_create(user=user)

        if val1 == 2:
            #user's score declared in model increase 5points
            #display correct and 5 points added to user
            user_score.score += 5
            user_score.save()
            return user_score
        else:
            #user's score declared in model has no point
            #display incorrect and 0 point added to user
            return user_score

    ans1 = request.GET.get('ans1', '')
    if ans1 == '':
        ans1 = 0

    cScore = verifyGame1(int(ans1))

    return render(request, 'morse_logs/game1.html', {'currentS': cScore})

morse_log/morse_logs/templates/morse_logs/base.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
</head>

<body>
    <div class="container ">
        <nav class="navbar navbar-inverse navbar-fixed-top"
            style="background-color: #2d2d30; font-size: 18px !important; font-family: Montserrat, sans-serif;">
            <div class="container-fluid ">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'morse_logs:index' %}"><span
                            class="glyphicon glyphicon-record"></span> Morse Code App</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'morse_logs:index' %}">Home</a></li>
                        <li><a href="{% url 'morse_logs:tutorialIndex' %}">Tutorials</a></li>
                        <li><a href="{% url 'morse_logs:gameDirectory' %}">Game</a></li>
                        <li><a href="{% url 'morse_logs:cipher' %}">Cipher</a></li>
                        <li><a href="{% url 'morse_logs:decipher' %}">Decipher</a></li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'users:view_profile' %}"><span class="glyphicon glyphicon-user"></span>
                                Profile </a></li>
                        <li><a href="{% url 'users:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Log out
                            </a></li>
                        {% else %}
                        <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a>
                        </li>
                        <li><a href="{% url 'users:register' %}"><span class="glyphicon glyphicon-pencil"></span>
                                Register</a></li>
                        {% endif %}
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
            <!--/.container-fluid -->
        </nav>
    </div>


    <br /><br /><br />
    <div class="container">
        <div class="row">
            <div class="col-sm6 col-sm-offset-3">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
</body>

morse_log/morse_logs/templates/morse_logs/cipher.html
{% extends "morse_logs/base.html" %}

{% block content %}
<title>Cipher</title>
<div class="container">
<h1>Cipher</h1>
    <div class="form-group form-group-lg">
    <form action="" method="get" >
<!--        <input class="form-control input-lg" id="inputlg" type="text" name="a1">-->
        <textarea rows="10" cols="50" name='a1' ></textarea>
        <textarea rows="10" cols="50" name='a2' > {{result}} </textarea>
        <button type="submit" name="decipher">Decipher</button>
    </form>
    </div>
</div>
{% endblock content  %}

morse_log/morse_logs/templates/morse_logs/decipher.html
{% extends "morse_logs/base.html" %}

{% block content %}
<title>Decipher</title>
<div class="container">
    <h1>Decipher</h1>
        <form action="" method="get" >
            <textarea rows="10" cols="50" name='a1' ></textarea>
            <textarea rows="10" cols="50" name='a2' > {{result}} </textarea>
            <button type="submit" name="decipher">Cipher</button>
        </form>
</div>
{% endblock content  %}

morse_log/morse_logs/templates/morse_logs/game1.html
{% extends "morse_logs/base.html" %}

{% block content %}
    <title>GAME 1</title>
    <h1>GAME 1</h1>
    <h2>1 + 1 = ?</h2>
    <form action="" method="get" >
        <input type="number" id="ans1" name="ans1"/><br><br>
        <button type="submit" name="game1Answer">Submit</button><br><br>
        <textarea rows="10" cols="50" name='a2' > {{currentS.score}} </textarea>
    </form>
</div>
{% endblock content %}

morse_log/morse_logs/templates/morse_logs/gameDirectory.html
{% extends "morse_logs/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'morse_logs/css/style.css' %}">
<div class="container">
    <title>Game Index</title>
    <h1>GAME INDEX</h1>
    <a href="{% url 'morse_logs:game1' %}">Game 1</a>
</div>
{% endblock content %}

morse_log/morse_logs/templates/morse_logs/index.html
{% extends "morse_logs/base.html" %}

{% block content %}
{% load static %}
<title>Home</title>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style>
.carousel{
    background: #2f4357;
    margin-top: 20px;
}
.carousel-item{
    text-align: center;
    min-height: 280px; /* Prevent carousel from being distorted if for some reason image doesn't load */
}
.bs-example{
	margin: 20px;
}
</style>
</head>
<div class="bs-example">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Carousel indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Wrapper for carousel items -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'morse_logs/img/A.jpg' %}" alt="First Slide">
            </div>
            <div class="carousel-item">
                <img src="{% static 'morse_logs/img/B.jpg' %}" alt="Second Slide">
            </div>
            <div class="carousel-item">
                <img src="{% static 'morse_logs/img/C.jpg' %}" alt="Third Slide">
            </div>
        </div>
        <!-- Carousel controls -->
        <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</div>

{% endblock content %}

morse_log/morse_logs/templates/morse_logs/topics.html
{% block content %}
<script type="text/javascript" src="/books/media/js/jquery-1.4.2.min.js" />
{% load static %}
<link rel="stylesheet" href="{% static 'morse_logs/css/style.css' %}">


<link href="{% static 'morse_logs/js/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
<link href="{% static 'morse_logs/js/jquery-ui/jquery-ui.structure.min.css' %}" rel="stylesheet">
<link href="{% static 'morse_logs/js/jquery-ui/jquery-ui.theme.min.css' %}" rel="stylesheet">

<div class="container">
    <title>Tutorial</title>
    <h1>Tutorial</h1>
</div>

<div class="col-sm-3">
    <div class="btn-group-vertical" style="padding-top:12px;">
        <button type="button" class="btn btn-warning" id="btn1" data-target="pilot">Btn1</button>
        <button type="button" class="btn btn-warning" id="btn2" data-target="design">Btn2</button>
        <button type="button" class="btn btn-warning" id="btn3" data-target="instrument">Btn3</button>
        <button type="button" class="btn btn-warning" id="btn4" data-target="innovations">Btn4</button>
    </div>
</div>
<div id="content" class="col-sm-9">
    <div id="pilot">
        <p>Name1</p>
        <h4>my name is A..........</h4>
    </div>
    <div id="design">
        <p>Name2</p>
        <h4>my name is A..........</h4>
    </div>
    <div id="instrument">
        <p>Name3</p>
        <h4>my name is A..........</h4>
    </div>
    <div id="innovations">
        <p>Name4</p>
        <h4>my name is A..........</h4>
    </div>
</div>

<script src="{% static 'morse_logs/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'morse_logs/js/jquery-ui/jquery-ui.js' %}"></script>
<script src="{% static 'morse_logs/js/app.js' %}"></script>
{% endblock content %}